ALTER TABLE "HistoryRecord" ADD COLUMN "keyPointsCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "HistoryRecord" ADD COLUMN "tasksTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "HistoryRecord" ADD COLUMN "tasksDone" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "HistoryRecord" ADD COLUMN "snapshotSummary" TEXT NOT NULL DEFAULT '[]';
